### PR TITLE
Skip promisify + await when nothing follows

### PR DESCRIPTION
**Pull request by bfred-it**

### CODE REVIEW

**Comment by bfred-it** [comment]
Closing for the same reason as https://github.com/sindresorhus/move-file/pull/1#issuecomment-341879634, although this situation isn't covered by tests like that one.

**Comment by bfred-it** [comment]
Related: I'm still annoyed that `node` went for the noisy `util.promisify` instead of just providing `fs/promise`

**Comment by sindresorhus** [comment]
@bfred-it You and me both (!!), but Node.js core is over-conservative, and it's better than nothing. I still dream about doing my own Node.js fork once in awhile, but time...

**Comment by bfred-it** [comment]
Good luck! If you do, use this name: `node.ss`

**Pull request closed without merging**
